# Generated by Django 5.1.1 on 2024-10-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('organic', 'organic'), ('furniture', 'furniture'), ('food', 'food'), ('cosmetics', 'cosmetics'), ('accessories', 'accessories')])),
                ('price', models.IntegerField()),
                ('image', models.TextField()),
                ('brand_id', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
