# Generated by Django 5.1.1 on 2024-10-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='creator_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='creator_id',
            field=models.IntegerField(default=1),
        ),
    ]
